### ISSUE TITLE
这个问题出现的原因是是什么？为什么这么解决？

### ISSUE THREAD

**Issue by OsBelief** [AliMaster/diary#1]
https://github.com/AliMaster/diary/blob/master/article/%E4%B8%80%E4%BA%9B%E7%B3%BB%E7%BB%9F%E5%BC%82%E5%B8%B8%E5%92%8C%E8%A7%A3%E5%86%B3%E6%96%B9%E6%B3%95.md

**Comment by AliMaster** [comment]
系统bug，辅助功能中的文字转语音模块。这里用的反射调用AccessibilityManager的私有方法setstate（0）来关掉辅助功能以解决这个问题。源码请看这里
http://grepcode.com/file/repo1.maven.org/maven2/org.robolectric/android-all/4.2.2_r1.2-robolectric-0/android/view/accessibility/AccessibilityManager.java#AccessibilityManager.setState%28int%29
